// Code generated by protoc-gen-go. DO NOT EDIT.
// source: document/v1/document.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Provides a Collection type for storing documents
type Collection struct {
	// The collection name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Optional parent key, required when the collection is a sub-collection of another document
	Parent               *Key     `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collection) Reset()         { *m = Collection{} }
func (m *Collection) String() string { return proto.CompactTextString(m) }
func (*Collection) ProtoMessage()    {}
func (*Collection) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{0}
}

func (m *Collection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collection.Unmarshal(m, b)
}
func (m *Collection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collection.Marshal(b, m, deterministic)
}
func (m *Collection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collection.Merge(m, src)
}
func (m *Collection) XXX_Size() int {
	return xxx_messageInfo_Collection.Size(m)
}
func (m *Collection) XXX_DiscardUnknown() {
	xxx_messageInfo_Collection.DiscardUnknown(m)
}

var xxx_messageInfo_Collection proto.InternalMessageInfo

func (m *Collection) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Collection) GetParent() *Key {
	if m != nil {
		return m.Parent
	}
	return nil
}

// Provides a document identifying key type
type Key struct {
	// The item collection
	Collection *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// The items unique id
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{1}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Provides a return document type
type Document struct {
	// The document content (JSON object)
	Content *_struct.Struct `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// The document's unique key, including collection/sub-collections
	Key                  *Key     `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{2}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetContent() *_struct.Struct {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Document) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type ExpressionValue struct {
	// The kind of value.
	//
	// Types that are valid to be assigned to Kind:
	//	*ExpressionValue_IntValue
	//	*ExpressionValue_DoubleValue
	//	*ExpressionValue_StringValue
	//	*ExpressionValue_BoolValue
	Kind                 isExpressionValue_Kind `protobuf_oneof:"kind"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ExpressionValue) Reset()         { *m = ExpressionValue{} }
func (m *ExpressionValue) String() string { return proto.CompactTextString(m) }
func (*ExpressionValue) ProtoMessage()    {}
func (*ExpressionValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{3}
}

func (m *ExpressionValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExpressionValue.Unmarshal(m, b)
}
func (m *ExpressionValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExpressionValue.Marshal(b, m, deterministic)
}
func (m *ExpressionValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExpressionValue.Merge(m, src)
}
func (m *ExpressionValue) XXX_Size() int {
	return xxx_messageInfo_ExpressionValue.Size(m)
}
func (m *ExpressionValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ExpressionValue.DiscardUnknown(m)
}

var xxx_messageInfo_ExpressionValue proto.InternalMessageInfo

type isExpressionValue_Kind interface {
	isExpressionValue_Kind()
}

type ExpressionValue_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type ExpressionValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type ExpressionValue_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type ExpressionValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*ExpressionValue_IntValue) isExpressionValue_Kind() {}

func (*ExpressionValue_DoubleValue) isExpressionValue_Kind() {}

func (*ExpressionValue_StringValue) isExpressionValue_Kind() {}

func (*ExpressionValue_BoolValue) isExpressionValue_Kind() {}

func (m *ExpressionValue) GetKind() isExpressionValue_Kind {
	if m != nil {
		return m.Kind
	}
	return nil
}

func (m *ExpressionValue) GetIntValue() int64 {
	if x, ok := m.GetKind().(*ExpressionValue_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *ExpressionValue) GetDoubleValue() float64 {
	if x, ok := m.GetKind().(*ExpressionValue_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *ExpressionValue) GetStringValue() string {
	if x, ok := m.GetKind().(*ExpressionValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *ExpressionValue) GetBoolValue() bool {
	if x, ok := m.GetKind().(*ExpressionValue_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ExpressionValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ExpressionValue_IntValue)(nil),
		(*ExpressionValue_DoubleValue)(nil),
		(*ExpressionValue_StringValue)(nil),
		(*ExpressionValue_BoolValue)(nil),
	}
}

// Provides a query expression type
type Expression struct {
	// The query operand or attribute
	Operand string `protobuf:"bytes,1,opt,name=operand,proto3" json:"operand,omitempty"`
	// The query operator [ == | < | <= | > | >= | startsWith ]
	Operator string `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	// The query expression value
	Value                *ExpressionValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Expression) Reset()         { *m = Expression{} }
func (m *Expression) String() string { return proto.CompactTextString(m) }
func (*Expression) ProtoMessage()    {}
func (*Expression) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{4}
}

func (m *Expression) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Expression.Unmarshal(m, b)
}
func (m *Expression) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Expression.Marshal(b, m, deterministic)
}
func (m *Expression) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Expression.Merge(m, src)
}
func (m *Expression) XXX_Size() int {
	return xxx_messageInfo_Expression.Size(m)
}
func (m *Expression) XXX_DiscardUnknown() {
	xxx_messageInfo_Expression.DiscardUnknown(m)
}

var xxx_messageInfo_Expression proto.InternalMessageInfo

func (m *Expression) GetOperand() string {
	if m != nil {
		return m.Operand
	}
	return ""
}

func (m *Expression) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *Expression) GetValue() *ExpressionValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type DocumentGetRequest struct {
	// Key of the document to retrieve
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentGetRequest) Reset()         { *m = DocumentGetRequest{} }
func (m *DocumentGetRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentGetRequest) ProtoMessage()    {}
func (*DocumentGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{5}
}

func (m *DocumentGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentGetRequest.Unmarshal(m, b)
}
func (m *DocumentGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentGetRequest.Marshal(b, m, deterministic)
}
func (m *DocumentGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentGetRequest.Merge(m, src)
}
func (m *DocumentGetRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentGetRequest.Size(m)
}
func (m *DocumentGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentGetRequest proto.InternalMessageInfo

func (m *DocumentGetRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type DocumentGetResponse struct {
	// The retrieved value
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentGetResponse) Reset()         { *m = DocumentGetResponse{} }
func (m *DocumentGetResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentGetResponse) ProtoMessage()    {}
func (*DocumentGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{6}
}

func (m *DocumentGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentGetResponse.Unmarshal(m, b)
}
func (m *DocumentGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentGetResponse.Marshal(b, m, deterministic)
}
func (m *DocumentGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentGetResponse.Merge(m, src)
}
func (m *DocumentGetResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentGetResponse.Size(m)
}
func (m *DocumentGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentGetResponse proto.InternalMessageInfo

func (m *DocumentGetResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DocumentSetRequest struct {
	// Key of the document to set
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The document content to store (JSON object)
	Content              *_struct.Struct `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DocumentSetRequest) Reset()         { *m = DocumentSetRequest{} }
func (m *DocumentSetRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentSetRequest) ProtoMessage()    {}
func (*DocumentSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{7}
}

func (m *DocumentSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentSetRequest.Unmarshal(m, b)
}
func (m *DocumentSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentSetRequest.Marshal(b, m, deterministic)
}
func (m *DocumentSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentSetRequest.Merge(m, src)
}
func (m *DocumentSetRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentSetRequest.Size(m)
}
func (m *DocumentSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentSetRequest proto.InternalMessageInfo

func (m *DocumentSetRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DocumentSetRequest) GetContent() *_struct.Struct {
	if m != nil {
		return m.Content
	}
	return nil
}

type DocumentSetResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentSetResponse) Reset()         { *m = DocumentSetResponse{} }
func (m *DocumentSetResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentSetResponse) ProtoMessage()    {}
func (*DocumentSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{8}
}

func (m *DocumentSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentSetResponse.Unmarshal(m, b)
}
func (m *DocumentSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentSetResponse.Marshal(b, m, deterministic)
}
func (m *DocumentSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentSetResponse.Merge(m, src)
}
func (m *DocumentSetResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentSetResponse.Size(m)
}
func (m *DocumentSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentSetResponse proto.InternalMessageInfo

type DocumentDeleteRequest struct {
	// Key of the document to delete
	Key                  *Key     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentDeleteRequest) Reset()         { *m = DocumentDeleteRequest{} }
func (m *DocumentDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentDeleteRequest) ProtoMessage()    {}
func (*DocumentDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{9}
}

func (m *DocumentDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentDeleteRequest.Unmarshal(m, b)
}
func (m *DocumentDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentDeleteRequest.Marshal(b, m, deterministic)
}
func (m *DocumentDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentDeleteRequest.Merge(m, src)
}
func (m *DocumentDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentDeleteRequest.Size(m)
}
func (m *DocumentDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentDeleteRequest proto.InternalMessageInfo

func (m *DocumentDeleteRequest) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

type DocumentDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentDeleteResponse) Reset()         { *m = DocumentDeleteResponse{} }
func (m *DocumentDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentDeleteResponse) ProtoMessage()    {}
func (*DocumentDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{10}
}

func (m *DocumentDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentDeleteResponse.Unmarshal(m, b)
}
func (m *DocumentDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentDeleteResponse.Marshal(b, m, deterministic)
}
func (m *DocumentDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentDeleteResponse.Merge(m, src)
}
func (m *DocumentDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentDeleteResponse.Size(m)
}
func (m *DocumentDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentDeleteResponse proto.InternalMessageInfo

type DocumentQueryRequest struct {
	// The collection to query
	Collection *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// Optional query expressions
	Expressions []*Expression `protobuf:"bytes,3,rep,name=expressions,proto3" json:"expressions,omitempty"`
	// Optional query fetch limit
	Limit int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional query paging continuation token
	PagingToken          map[string]string `protobuf:"bytes,5,rep,name=paging_token,json=pagingToken,proto3" json:"paging_token,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DocumentQueryRequest) Reset()         { *m = DocumentQueryRequest{} }
func (m *DocumentQueryRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentQueryRequest) ProtoMessage()    {}
func (*DocumentQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{11}
}

func (m *DocumentQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentQueryRequest.Unmarshal(m, b)
}
func (m *DocumentQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentQueryRequest.Marshal(b, m, deterministic)
}
func (m *DocumentQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentQueryRequest.Merge(m, src)
}
func (m *DocumentQueryRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentQueryRequest.Size(m)
}
func (m *DocumentQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentQueryRequest proto.InternalMessageInfo

func (m *DocumentQueryRequest) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

func (m *DocumentQueryRequest) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *DocumentQueryRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *DocumentQueryRequest) GetPagingToken() map[string]string {
	if m != nil {
		return m.PagingToken
	}
	return nil
}

type DocumentQueryResponse struct {
	// The retrieved values
	Documents []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	// The query paging continuation token, when empty no further results are available
	PagingToken          map[string]string `protobuf:"bytes,2,rep,name=paging_token,json=pagingToken,proto3" json:"paging_token,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DocumentQueryResponse) Reset()         { *m = DocumentQueryResponse{} }
func (m *DocumentQueryResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentQueryResponse) ProtoMessage()    {}
func (*DocumentQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{12}
}

func (m *DocumentQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentQueryResponse.Unmarshal(m, b)
}
func (m *DocumentQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentQueryResponse.Marshal(b, m, deterministic)
}
func (m *DocumentQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentQueryResponse.Merge(m, src)
}
func (m *DocumentQueryResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentQueryResponse.Size(m)
}
func (m *DocumentQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentQueryResponse proto.InternalMessageInfo

func (m *DocumentQueryResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

func (m *DocumentQueryResponse) GetPagingToken() map[string]string {
	if m != nil {
		return m.PagingToken
	}
	return nil
}

type DocumentQueryStreamRequest struct {
	// The collection to query
	Collection *Collection `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	// Optional query expressions
	Expressions []*Expression `protobuf:"bytes,3,rep,name=expressions,proto3" json:"expressions,omitempty"`
	// Optional query fetch limit
	Limit                int32    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DocumentQueryStreamRequest) Reset()         { *m = DocumentQueryStreamRequest{} }
func (m *DocumentQueryStreamRequest) String() string { return proto.CompactTextString(m) }
func (*DocumentQueryStreamRequest) ProtoMessage()    {}
func (*DocumentQueryStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{13}
}

func (m *DocumentQueryStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentQueryStreamRequest.Unmarshal(m, b)
}
func (m *DocumentQueryStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentQueryStreamRequest.Marshal(b, m, deterministic)
}
func (m *DocumentQueryStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentQueryStreamRequest.Merge(m, src)
}
func (m *DocumentQueryStreamRequest) XXX_Size() int {
	return xxx_messageInfo_DocumentQueryStreamRequest.Size(m)
}
func (m *DocumentQueryStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentQueryStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentQueryStreamRequest proto.InternalMessageInfo

func (m *DocumentQueryStreamRequest) GetCollection() *Collection {
	if m != nil {
		return m.Collection
	}
	return nil
}

func (m *DocumentQueryStreamRequest) GetExpressions() []*Expression {
	if m != nil {
		return m.Expressions
	}
	return nil
}

func (m *DocumentQueryStreamRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type DocumentQueryStreamResponse struct {
	// The stream document
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentQueryStreamResponse) Reset()         { *m = DocumentQueryStreamResponse{} }
func (m *DocumentQueryStreamResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentQueryStreamResponse) ProtoMessage()    {}
func (*DocumentQueryStreamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3f8d05af3d8df6c9, []int{14}
}

func (m *DocumentQueryStreamResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentQueryStreamResponse.Unmarshal(m, b)
}
func (m *DocumentQueryStreamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentQueryStreamResponse.Marshal(b, m, deterministic)
}
func (m *DocumentQueryStreamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentQueryStreamResponse.Merge(m, src)
}
func (m *DocumentQueryStreamResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentQueryStreamResponse.Size(m)
}
func (m *DocumentQueryStreamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentQueryStreamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentQueryStreamResponse proto.InternalMessageInfo

func (m *DocumentQueryStreamResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

func init() {
	proto.RegisterType((*Collection)(nil), "nitric.document.v1.Collection")
	proto.RegisterType((*Key)(nil), "nitric.document.v1.Key")
	proto.RegisterType((*Document)(nil), "nitric.document.v1.Document")
	proto.RegisterType((*ExpressionValue)(nil), "nitric.document.v1.ExpressionValue")
	proto.RegisterType((*Expression)(nil), "nitric.document.v1.Expression")
	proto.RegisterType((*DocumentGetRequest)(nil), "nitric.document.v1.DocumentGetRequest")
	proto.RegisterType((*DocumentGetResponse)(nil), "nitric.document.v1.DocumentGetResponse")
	proto.RegisterType((*DocumentSetRequest)(nil), "nitric.document.v1.DocumentSetRequest")
	proto.RegisterType((*DocumentSetResponse)(nil), "nitric.document.v1.DocumentSetResponse")
	proto.RegisterType((*DocumentDeleteRequest)(nil), "nitric.document.v1.DocumentDeleteRequest")
	proto.RegisterType((*DocumentDeleteResponse)(nil), "nitric.document.v1.DocumentDeleteResponse")
	proto.RegisterType((*DocumentQueryRequest)(nil), "nitric.document.v1.DocumentQueryRequest")
	proto.RegisterMapType((map[string]string)(nil), "nitric.document.v1.DocumentQueryRequest.PagingTokenEntry")
	proto.RegisterType((*DocumentQueryResponse)(nil), "nitric.document.v1.DocumentQueryResponse")
	proto.RegisterMapType((map[string]string)(nil), "nitric.document.v1.DocumentQueryResponse.PagingTokenEntry")
	proto.RegisterType((*DocumentQueryStreamRequest)(nil), "nitric.document.v1.DocumentQueryStreamRequest")
	proto.RegisterType((*DocumentQueryStreamResponse)(nil), "nitric.document.v1.DocumentQueryStreamResponse")
}

func init() { proto.RegisterFile("document/v1/document.proto", fileDescriptor_3f8d05af3d8df6c9) }

var fileDescriptor_3f8d05af3d8df6c9 = []byte{
	// 868 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0xce, 0xd8, 0xd9, 0x74, 0xf7, 0x6d, 0xa4, 0x46, 0x43, 0x42, 0x2c, 0xb7, 0x94, 0x95, 0x83,
	0x60, 0x93, 0x0a, 0x9b, 0xdd, 0x5e, 0x4a, 0xda, 0x04, 0xe4, 0xa6, 0x6a, 0x50, 0x11, 0x84, 0x59,
	0x94, 0x4a, 0xe0, 0x52, 0x39, 0xbb, 0x43, 0x18, 0xc5, 0x3b, 0x63, 0xec, 0xd9, 0x2d, 0x2b, 0x38,
	0x70, 0xe2, 0xc0, 0xdf, 0xe0, 0x86, 0xf8, 0x0d, 0xfc, 0x00, 0x7e, 0x00, 0x3f, 0xa4, 0xc7, 0x9c,
	0x90, 0xc7, 0x9e, 0xb5, 0x13, 0xc2, 0x66, 0xa3, 0xc0, 0x81, 0x9b, 0x67, 0xe6, 0xfb, 0xde, 0xf7,
	0xbd, 0x37, 0x6f, 0x9e, 0xc1, 0x1e, 0x88, 0xfe, 0x68, 0x48, 0xb9, 0xf4, 0xc6, 0x1d, 0x4f, 0x7f,
	0xbb, 0x71, 0x22, 0xa4, 0xc0, 0x98, 0x33, 0x99, 0xb0, 0xbe, 0x3b, 0xdd, 0x1e, 0x77, 0xec, 0xdb,
	0xc7, 0x42, 0x1c, 0x47, 0xd4, 0x53, 0x88, 0xa3, 0xd1, 0xd7, 0x5e, 0x2a, 0x93, 0x51, 0xbf, 0x60,
	0xd8, 0xeb, 0xe3, 0x30, 0x62, 0x83, 0x50, 0x52, 0x4f, 0x7f, 0xe4, 0x07, 0xce, 0x10, 0xe0, 0x91,
	0x88, 0x22, 0xda, 0x97, 0x4c, 0x70, 0xec, 0xc2, 0x22, 0x0f, 0x87, 0xd4, 0x42, 0x2d, 0xd4, 0x6e,
	0xf8, 0xf6, 0xa9, 0xbf, 0x9e, 0xac, 0xb5, 0x7f, 0x34, 0xba, 0x2b, 0x5f, 0x05, 0x2f, 0xef, 0xb6,
	0xbf, 0x74, 0x83, 0x77, 0x9f, 0x07, 0x2f, 0xef, 0x6e, 0x6e, 0xbd, 0x45, 0x14, 0x0e, 0x7b, 0xb0,
	0x14, 0x87, 0x09, 0xe5, 0xd2, 0x32, 0x5a, 0xa8, 0xdd, 0xec, 0xae, 0xbb, 0x7f, 0x77, 0xe6, 0x3e,
	0xa5, 0x13, 0x52, 0xc0, 0x9c, 0xef, 0xc1, 0x7c, 0x4a, 0x27, 0x78, 0x1f, 0xa0, 0x3f, 0x55, 0x55,
	0x6a, 0xcd, 0xee, 0x9d, 0x8b, 0xb8, 0xa5, 0x37, 0xbf, 0x7e, 0xea, 0xd7, 0x7e, 0x46, 0xc6, 0x0a,
	0x22, 0x15, 0x2e, 0xde, 0x02, 0x83, 0x0d, 0x94, 0xfa, 0x6c, 0xbf, 0x06, 0x1b, 0x38, 0x3f, 0x40,
	0x7d, 0xaf, 0x88, 0x8d, 0x1f, 0xc0, 0x8d, 0xbe, 0xe0, 0x32, 0xb3, 0x8e, 0x0a, 0xeb, 0x79, 0x01,
	0x5d, 0x5d, 0x40, 0xb7, 0xa7, 0x0a, 0x58, 0xd1, 0xd5, 0x0c, 0x7c, 0x0f, 0xcc, 0x13, 0x3a, 0xb9,
	0x24, 0xe7, 0x0a, 0x31, 0x43, 0x3b, 0xbf, 0x20, 0xb8, 0xf9, 0xf8, 0xbb, 0x38, 0xa1, 0x69, 0xca,
	0x04, 0x3f, 0x0c, 0xa3, 0x11, 0xc5, 0x6f, 0x40, 0x83, 0x71, 0xf9, 0x62, 0x9c, 0x2d, 0x94, 0x0f,
	0x73, 0x7f, 0x81, 0xd4, 0x19, 0x97, 0xf9, 0xf1, 0x06, 0x2c, 0x0f, 0xc4, 0xe8, 0x28, 0xa2, 0x05,
	0x22, 0x13, 0x44, 0xfb, 0x0b, 0xa4, 0x99, 0xef, 0x4e, 0x41, 0xa9, 0x4c, 0x18, 0x3f, 0x2e, 0x40,
	0x66, 0x56, 0x8b, 0x0c, 0x94, 0xef, 0xe6, 0xa0, 0x37, 0x01, 0x8e, 0x84, 0x88, 0x0a, 0xc8, 0x62,
	0x0b, 0xb5, 0xeb, 0xfb, 0x0b, 0xa4, 0x91, 0xed, 0x29, 0x80, 0xbf, 0x04, 0x8b, 0x27, 0x8c, 0x0f,
	0x9c, 0xdf, 0x10, 0x40, 0xe9, 0x12, 0x5b, 0x70, 0x43, 0xc4, 0x34, 0x09, 0xf9, 0x20, 0xef, 0x09,
	0xa2, 0x97, 0xf8, 0x03, 0xa8, 0xab, 0x4f, 0x29, 0x92, 0xa2, 0xfc, 0x1b, 0xa7, 0x7e, 0x2b, 0xb9,
	0x43, 0x8c, 0x9d, 0x1d, 0x82, 0x1e, 0x12, 0xe3, 0xe1, 0x0e, 0x41, 0xbb, 0xc4, 0xd8, 0xdd, 0x21,
	0x90, 0xca, 0x30, 0x91, 0xe9, 0x33, 0x26, 0xbf, 0x21, 0x53, 0x12, 0x7e, 0x04, 0xb5, 0xd2, 0x70,
	0xb3, 0xbb, 0x71, 0x51, 0x19, 0xcf, 0xd5, 0xab, 0x52, 0xd2, 0x9c, 0xeb, 0x7c, 0x04, 0x58, 0x5f,
	0xe9, 0x13, 0x2a, 0x09, 0xfd, 0x76, 0x44, 0xd3, 0xe9, 0xfd, 0xa0, 0x2b, 0xdd, 0xcf, 0xa7, 0xf0,
	0xda, 0x99, 0x50, 0x69, 0x2c, 0x78, 0x4a, 0xf1, 0x7d, 0xa8, 0x6b, 0x62, 0x11, 0xf0, 0xf6, 0x45,
	0x01, 0x35, 0x95, 0x4c, 0xd1, 0xce, 0x4f, 0xa8, 0x34, 0xd7, 0xbb, 0x9e, 0xb9, 0x6a, 0xbb, 0x9a,
	0x57, 0x6d, 0x57, 0x67, 0xad, 0xcc, 0xac, 0x57, 0x66, 0xe6, 0x7c, 0x0c, 0x6b, 0x7a, 0x7b, 0x8f,
	0x46, 0x54, 0xd2, 0x6b, 0x95, 0xcf, 0x82, 0xd7, 0xcf, 0x47, 0x2b, 0x74, 0xfe, 0x34, 0x60, 0x55,
	0x1f, 0x7d, 0x36, 0xa2, 0xc9, 0x44, 0xeb, 0xfc, 0x7b, 0x53, 0xe0, 0x43, 0x68, 0xd2, 0x69, 0xab,
	0xa4, 0x96, 0xd9, 0x32, 0xff, 0x29, 0x54, 0xd9, 0x51, 0xa4, 0x4a, 0xc1, 0xab, 0x50, 0x8b, 0xd8,
	0x90, 0x49, 0xf5, 0x36, 0x6a, 0x24, 0x5f, 0xe0, 0x00, 0x96, 0xe3, 0xf0, 0x38, 0x7b, 0x5b, 0x52,
	0x9c, 0x50, 0x6e, 0xd5, 0x54, 0xe0, 0xf7, 0x67, 0x35, 0x40, 0x35, 0x43, 0xf7, 0x40, 0x91, 0x3f,
	0xcf, 0xb8, 0x8f, 0xb9, 0x4c, 0x26, 0xa4, 0x19, 0x97, 0x3b, 0xf6, 0x2e, 0xac, 0x9c, 0x07, 0xe0,
	0x95, 0xb2, 0xf6, 0x8d, 0xfc, 0xea, 0x57, 0xf5, 0x3b, 0x51, 0xaf, 0xac, 0x68, 0xfc, 0x6d, 0xe3,
	0x3e, 0x72, 0x5e, 0xa1, 0xf2, 0x06, 0x0b, 0xd9, 0xa2, 0x69, 0xb7, 0xa1, 0xa1, 0xbd, 0xa5, 0x16,
	0x52, 0xa6, 0x67, 0x77, 0x6d, 0x09, 0xc7, 0xcf, 0xcf, 0xe5, 0x6c, 0x28, 0xfa, 0xf6, 0x1c, 0x39,
	0xe7, 0xe2, 0xff, 0x71, 0xd2, 0xbf, 0x23, 0xb0, 0xcf, 0xe8, 0xf6, 0x64, 0x42, 0xc3, 0xe1, 0xff,
	0xa6, 0xa7, 0x9c, 0x67, 0x70, 0xeb, 0x42, 0xff, 0xd7, 0x9d, 0x37, 0xdd, 0x57, 0x26, 0xdc, 0x2c,
	0xdf, 0x79, 0x32, 0x66, 0x7d, 0x8a, 0x0f, 0xc1, 0x7c, 0x42, 0x25, 0x7e, 0x7b, 0x56, 0x88, 0x72,
	0x70, 0xda, 0xef, 0x5c, 0x8a, 0x2b, 0x5c, 0x1e, 0x82, 0xd9, 0xbb, 0x2c, 0x6e, 0x6f, 0xce, 0xb8,
	0x95, 0x99, 0x84, 0x5f, 0xc0, 0x52, 0x3e, 0x3d, 0xf0, 0xe6, 0x2c, 0xca, 0x99, 0x79, 0x65, 0x6f,
	0xcd, 0x03, 0x2d, 0x04, 0x02, 0xa8, 0xa9, 0xaa, 0xe3, 0xf6, 0xbc, 0x8f, 0xd8, 0xde, 0x9c, 0xbb,
	0xf5, 0x71, 0x0c, 0xcd, 0xca, 0x9d, 0x62, 0xf7, 0x52, 0xe6, 0x99, 0xe6, 0xb5, 0xbd, 0xb9, 0xf1,
	0xb9, 0xde, 0x7b, 0xc8, 0xe7, 0x70, 0x8b, 0x09, 0x4d, 0x53, 0xff, 0x82, 0x2a, 0xd9, 0x6f, 0x68,
	0x76, 0x7a, 0x80, 0xbe, 0x58, 0xce, 0x61, 0xde, 0xb8, 0xf3, 0x60, 0xdc, 0xf9, 0xd5, 0xb0, 0x3e,
	0xc9, 0x59, 0x07, 0x8a, 0xb5, 0x57, 0xb2, 0xfe, 0xd0, 0x47, 0x81, 0x3a, 0x0a, 0xf4, 0x51, 0x70,
	0xd8, 0x39, 0x5a, 0x52, 0x1a, 0xf7, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x54, 0x34, 0x5c, 0xa3,
	0x9f, 0x0a, 0x00, 0x00,
}
