// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event/v1/event.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request to publish an event to a topic
type EventPublishRequest struct {
	// The name of the topic to publish the event to
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	// The event to be published
	Event                *NitricEvent `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *EventPublishRequest) Reset()         { *m = EventPublishRequest{} }
func (m *EventPublishRequest) String() string { return proto.CompactTextString(m) }
func (*EventPublishRequest) ProtoMessage()    {}
func (*EventPublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f857b978571765b2, []int{0}
}

func (m *EventPublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPublishRequest.Unmarshal(m, b)
}
func (m *EventPublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPublishRequest.Marshal(b, m, deterministic)
}
func (m *EventPublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPublishRequest.Merge(m, src)
}
func (m *EventPublishRequest) XXX_Size() int {
	return xxx_messageInfo_EventPublishRequest.Size(m)
}
func (m *EventPublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventPublishRequest proto.InternalMessageInfo

func (m *EventPublishRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *EventPublishRequest) GetEvent() *NitricEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

// Result of publishing an event
type EventPublishResponse struct {
	// The id of the published message
	// When an id was not supplied
	// one should be automatically generated
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventPublishResponse) Reset()         { *m = EventPublishResponse{} }
func (m *EventPublishResponse) String() string { return proto.CompactTextString(m) }
func (*EventPublishResponse) ProtoMessage()    {}
func (*EventPublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f857b978571765b2, []int{1}
}

func (m *EventPublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventPublishResponse.Unmarshal(m, b)
}
func (m *EventPublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventPublishResponse.Marshal(b, m, deterministic)
}
func (m *EventPublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventPublishResponse.Merge(m, src)
}
func (m *EventPublishResponse) XXX_Size() int {
	return xxx_messageInfo_EventPublishResponse.Size(m)
}
func (m *EventPublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EventPublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EventPublishResponse proto.InternalMessageInfo

func (m *EventPublishResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Request for the Topic List method
type TopicListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicListRequest) Reset()         { *m = TopicListRequest{} }
func (m *TopicListRequest) String() string { return proto.CompactTextString(m) }
func (*TopicListRequest) ProtoMessage()    {}
func (*TopicListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f857b978571765b2, []int{2}
}

func (m *TopicListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicListRequest.Unmarshal(m, b)
}
func (m *TopicListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicListRequest.Marshal(b, m, deterministic)
}
func (m *TopicListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicListRequest.Merge(m, src)
}
func (m *TopicListRequest) XXX_Size() int {
	return xxx_messageInfo_TopicListRequest.Size(m)
}
func (m *TopicListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TopicListRequest proto.InternalMessageInfo

// Topic List Response
type TopicListResponse struct {
	// The list of found topics
	Topics               []*NitricTopic `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TopicListResponse) Reset()         { *m = TopicListResponse{} }
func (m *TopicListResponse) String() string { return proto.CompactTextString(m) }
func (*TopicListResponse) ProtoMessage()    {}
func (*TopicListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f857b978571765b2, []int{3}
}

func (m *TopicListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicListResponse.Unmarshal(m, b)
}
func (m *TopicListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicListResponse.Marshal(b, m, deterministic)
}
func (m *TopicListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicListResponse.Merge(m, src)
}
func (m *TopicListResponse) XXX_Size() int {
	return xxx_messageInfo_TopicListResponse.Size(m)
}
func (m *TopicListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TopicListResponse proto.InternalMessageInfo

func (m *TopicListResponse) GetTopics() []*NitricTopic {
	if m != nil {
		return m.Topics
	}
	return nil
}

// Represents an event topic
type NitricTopic struct {
	// The Nitric name for the topic
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NitricTopic) Reset()         { *m = NitricTopic{} }
func (m *NitricTopic) String() string { return proto.CompactTextString(m) }
func (*NitricTopic) ProtoMessage()    {}
func (*NitricTopic) Descriptor() ([]byte, []int) {
	return fileDescriptor_f857b978571765b2, []int{4}
}

func (m *NitricTopic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NitricTopic.Unmarshal(m, b)
}
func (m *NitricTopic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NitricTopic.Marshal(b, m, deterministic)
}
func (m *NitricTopic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NitricTopic.Merge(m, src)
}
func (m *NitricTopic) XXX_Size() int {
	return xxx_messageInfo_NitricTopic.Size(m)
}
func (m *NitricTopic) XXX_DiscardUnknown() {
	xxx_messageInfo_NitricTopic.DiscardUnknown(m)
}

var xxx_messageInfo_NitricTopic proto.InternalMessageInfo

func (m *NitricTopic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Nitric Event Model
type NitricEvent struct {
	// A Unique ID for the Nitric Event
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A content hint for the events payload
	PayloadType string `protobuf:"bytes,2,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	// The payload of the event
	Payload              *_struct.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NitricEvent) Reset()         { *m = NitricEvent{} }
func (m *NitricEvent) String() string { return proto.CompactTextString(m) }
func (*NitricEvent) ProtoMessage()    {}
func (*NitricEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_f857b978571765b2, []int{5}
}

func (m *NitricEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NitricEvent.Unmarshal(m, b)
}
func (m *NitricEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NitricEvent.Marshal(b, m, deterministic)
}
func (m *NitricEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NitricEvent.Merge(m, src)
}
func (m *NitricEvent) XXX_Size() int {
	return xxx_messageInfo_NitricEvent.Size(m)
}
func (m *NitricEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NitricEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NitricEvent proto.InternalMessageInfo

func (m *NitricEvent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NitricEvent) GetPayloadType() string {
	if m != nil {
		return m.PayloadType
	}
	return ""
}

func (m *NitricEvent) GetPayload() *_struct.Struct {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*EventPublishRequest)(nil), "nitric.event.v1.EventPublishRequest")
	proto.RegisterType((*EventPublishResponse)(nil), "nitric.event.v1.EventPublishResponse")
	proto.RegisterType((*TopicListRequest)(nil), "nitric.event.v1.TopicListRequest")
	proto.RegisterType((*TopicListResponse)(nil), "nitric.event.v1.TopicListResponse")
	proto.RegisterType((*NitricTopic)(nil), "nitric.event.v1.NitricTopic")
	proto.RegisterType((*NitricEvent)(nil), "nitric.event.v1.NitricEvent")
}

func init() { proto.RegisterFile("event/v1/event.proto", fileDescriptor_f857b978571765b2) }

var fileDescriptor_f857b978571765b2 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xe5, 0x6c, 0xed, 0xd8, 0x6b, 0x05, 0xc5, 0x6c, 0x6a, 0x14, 0xed, 0xd0, 0x46, 0x03,
	0x15, 0x26, 0x1c, 0x52, 0xb8, 0xc1, 0x29, 0xd2, 0x0e, 0x48, 0x80, 0xaa, 0x6c, 0xda, 0x01, 0x32,
	0x50, 0xda, 0x78, 0xc3, 0x52, 0x88, 0x43, 0xec, 0x64, 0xea, 0x8d, 0x0b, 0x17, 0x3e, 0x0a, 0x1f,
	0x85, 0x8f, 0xb4, 0x13, 0xea, 0xb3, 0x83, 0x46, 0x87, 0xca, 0xcd, 0xfe, 0xfb, 0xf7, 0xfc, 0xfe,
	0xef, 0xff, 0x60, 0x8f, 0x37, 0xbc, 0xd0, 0x41, 0x13, 0x06, 0x78, 0x60, 0x65, 0x25, 0xb5, 0xa4,
	0xf7, 0x0a, 0xa1, 0x2b, 0xb1, 0x60, 0x46, 0x6b, 0x42, 0xef, 0xe0, 0x52, 0xca, 0xcb, 0x9c, 0x07,
	0xf8, 0x3c, 0xaf, 0x2f, 0x02, 0xa5, 0xab, 0x7a, 0x61, 0x71, 0x6f, 0xd8, 0xa4, 0xb9, 0xc8, 0x52,
	0xcd, 0x83, 0xf6, 0x60, 0x1e, 0xfc, 0xef, 0x04, 0x1e, 0x1c, 0xaf, 0xfe, 0x98, 0xd5, 0xf3, 0x5c,
	0xa8, 0xcf, 0x31, 0xff, 0x5a, 0x73, 0xa5, 0xe9, 0x33, 0xe8, 0x68, 0x59, 0x8a, 0x85, 0x4b, 0x46,
	0x64, 0xb2, 0x1b, 0x79, 0xd7, 0xd1, 0xb0, 0xda, 0x9f, 0x7c, 0x73, 0xa6, 0x83, 0x8f, 0xc9, 0xd5,
	0xd1, 0xe4, 0x03, 0x4b, 0x9e, 0x9e, 0x27, 0x57, 0x47, 0x8f, 0x9f, 0x1c, 0xc6, 0x06, 0xa4, 0xaf,
	0xa0, 0x83, 0x66, 0x5c, 0x67, 0x44, 0x26, 0xbd, 0xe9, 0x01, 0x5b, 0x73, 0xc8, 0xde, 0xe1, 0x1d,
	0x9b, 0x45, 0x77, 0xae, 0xa3, 0xce, 0x0f, 0xe2, 0x0c, 0x48, 0x6c, 0x8a, 0xfc, 0x47, 0xb0, 0xf7,
	0xb7, 0x0d, 0x55, 0xca, 0x42, 0x71, 0x7a, 0x17, 0x1c, 0x91, 0x19, 0x13, 0xb1, 0x23, 0x32, 0x9f,
	0xc2, 0xe0, 0x74, 0xd5, 0xee, 0x8d, 0x50, 0xda, 0x7a, 0xf5, 0x5f, 0xc3, 0xfd, 0x1b, 0x9a, 0x2d,
	0x7c, 0x01, 0x5d, 0xf4, 0xa5, 0x5c, 0x32, 0xda, 0xda, 0xe0, 0x07, 0x2b, 0x63, 0xcb, 0xfa, 0x63,
	0xe8, 0xdd, 0x90, 0x29, 0x85, 0xed, 0x22, 0xfd, 0xc2, 0x6d, 0x7f, 0x3c, 0xfb, 0xaa, 0x45, 0xd0,
	0xef, 0xba, 0x41, 0x3a, 0x86, 0x7e, 0x99, 0x2e, 0x73, 0x99, 0x66, 0x9f, 0xf4, 0xb2, 0xe4, 0x98,
	0xc6, 0x6e, 0xdc, 0xb3, 0xda, 0xe9, 0xb2, 0xe4, 0x34, 0x84, 0x1d, 0x7b, 0x75, 0xb7, 0x30, 0xab,
	0x21, 0x33, 0xcb, 0x63, 0xed, 0xf2, 0xd8, 0x09, 0x2e, 0x2f, 0x6e, 0xb9, 0xe9, 0x05, 0xf4, 0xb1,
	0xdd, 0x09, 0xaf, 0x1a, 0xb1, 0xe0, 0xf4, 0x0c, 0x76, 0x6c, 0x52, 0xf4, 0xf0, 0xd6, 0x60, 0xff,
	0xd8, 0xa7, 0xf7, 0xf0, 0x3f, 0x94, 0x49, 0x6d, 0x7a, 0x0e, 0x7d, 0x9c, 0xbc, 0xed, 0xf3, 0x16,
	0xb6, 0x57, 0xa9, 0xd2, 0xf1, 0xad, 0xf2, 0xf5, 0x2d, 0x78, 0xfe, 0x26, 0xc4, 0x7c, 0x1f, 0xcd,
	0xc1, 0x15, 0xb2, 0xe5, 0x70, 0xd8, 0x3f, 0x74, 0xd4, 0x45, 0x43, 0x6a, 0x46, 0xde, 0xf7, 0x0d,
	0x10, 0x34, 0xe1, 0xcb, 0x26, 0xfc, 0xe9, 0xec, 0x9b, 0xb8, 0xd9, 0x0c, 0xf9, 0x63, 0xcb, 0xff,
	0x6a, 0xf5, 0x04, 0xf5, 0x04, 0xf5, 0xe4, 0x2c, 0x9c, 0x77, 0xf1, 0xdf, 0xe7, 0xbf, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x34, 0x48, 0xe9, 0x65, 0x38, 0x03, 0x00, 0x00,
}
