// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: faas/v1/faas.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Messages the client is able to send to the server
type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Client message ID, used to pair requests/responses
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Content:
	//	*ClientMessage_InitRequest
	//	*ClientMessage_TriggerResponse
	Content isClientMessage_Content `protobuf_oneof:"content"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{0}
}

func (x *ClientMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *ClientMessage) GetContent() isClientMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ClientMessage) GetInitRequest() *InitRequest {
	if x, ok := x.GetContent().(*ClientMessage_InitRequest); ok {
		return x.InitRequest
	}
	return nil
}

func (x *ClientMessage) GetTriggerResponse() *TriggerResponse {
	if x, ok := x.GetContent().(*ClientMessage_TriggerResponse); ok {
		return x.TriggerResponse
	}
	return nil
}

type isClientMessage_Content interface {
	isClientMessage_Content()
}

type ClientMessage_InitRequest struct {
	// Client initialisation request
	InitRequest *InitRequest `protobuf:"bytes,2,opt,name=init_request,json=initRequest,proto3,oneof"`
}

type ClientMessage_TriggerResponse struct {
	// Client responsding with result of
	// a trigger
	TriggerResponse *TriggerResponse `protobuf:"bytes,3,opt,name=trigger_response,json=triggerResponse,proto3,oneof"`
}

func (*ClientMessage_InitRequest) isClientMessage_Content() {}

func (*ClientMessage_TriggerResponse) isClientMessage_Content() {}

// Messages the server is able to send to the client
type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Server message ID, used to pair requests/responses
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are assignable to Content:
	//	*ServerMessage_InitResponse
	//	*ServerMessage_TriggerRequest
	Content isServerMessage_Content `protobuf_oneof:"content"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{1}
}

func (x *ServerMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (m *ServerMessage) GetContent() isServerMessage_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ServerMessage) GetInitResponse() *InitResponse {
	if x, ok := x.GetContent().(*ServerMessage_InitResponse); ok {
		return x.InitResponse
	}
	return nil
}

func (x *ServerMessage) GetTriggerRequest() *TriggerRequest {
	if x, ok := x.GetContent().(*ServerMessage_TriggerRequest); ok {
		return x.TriggerRequest
	}
	return nil
}

type isServerMessage_Content interface {
	isServerMessage_Content()
}

type ServerMessage_InitResponse struct {
	// Server responding
	// with client configuration details to an
	// InitRequest
	InitResponse *InitResponse `protobuf:"bytes,2,opt,name=init_response,json=initResponse,proto3,oneof"`
}

type ServerMessage_TriggerRequest struct {
	// Server requesting client to
	// process a trigger
	TriggerRequest *TriggerRequest `protobuf:"bytes,3,opt,name=trigger_request,json=triggerRequest,proto3,oneof"`
}

func (*ServerMessage_InitResponse) isServerMessage_Content() {}

func (*ServerMessage_TriggerRequest) isServerMessage_Content() {}

// Placeholder message
type InitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{2}
}

// Placeholder message
type InitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{3}
}

// The server has a trigger for the client to handle
type TriggerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The data in the trigger
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Should we supply a mime type for the data?
	// Or rely on context?
	MimeType string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	// The context of the trigger
	//
	// Types that are assignable to Context:
	//	*TriggerRequest_Http
	//	*TriggerRequest_Topic
	Context isTriggerRequest_Context `protobuf_oneof:"context"`
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TriggerRequest) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (m *TriggerRequest) GetContext() isTriggerRequest_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (x *TriggerRequest) GetHttp() *HttpTriggerContext {
	if x, ok := x.GetContext().(*TriggerRequest_Http); ok {
		return x.Http
	}
	return nil
}

func (x *TriggerRequest) GetTopic() *TopicTriggerContext {
	if x, ok := x.GetContext().(*TriggerRequest_Topic); ok {
		return x.Topic
	}
	return nil
}

type isTriggerRequest_Context interface {
	isTriggerRequest_Context()
}

type TriggerRequest_Http struct {
	Http *HttpTriggerContext `protobuf:"bytes,3,opt,name=http,proto3,oneof"`
}

type TriggerRequest_Topic struct {
	Topic *TopicTriggerContext `protobuf:"bytes,4,opt,name=topic,proto3,oneof"`
}

func (*TriggerRequest_Http) isTriggerRequest_Context() {}

func (*TriggerRequest_Topic) isTriggerRequest_Context() {}

type HttpTriggerContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The request method
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// The path of the request
	Path string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// The request headers
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The query params (if parseable by the membrane)
	QueryParams map[string]string `protobuf:"bytes,4,rep,name=query_params,json=queryParams,proto3" json:"query_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *HttpTriggerContext) Reset() {
	*x = HttpTriggerContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpTriggerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpTriggerContext) ProtoMessage() {}

func (x *HttpTriggerContext) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpTriggerContext.ProtoReflect.Descriptor instead.
func (*HttpTriggerContext) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{5}
}

func (x *HttpTriggerContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpTriggerContext) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpTriggerContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpTriggerContext) GetQueryParams() map[string]string {
	if x != nil {
		return x.QueryParams
	}
	return nil
}

type TopicTriggerContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The topic the message was published for
	Topic string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
}

func (x *TopicTriggerContext) Reset() {
	*x = TopicTriggerContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicTriggerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicTriggerContext) ProtoMessage() {}

func (x *TopicTriggerContext) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicTriggerContext.ProtoReflect.Descriptor instead.
func (*TopicTriggerContext) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{6}
}

func (x *TopicTriggerContext) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// The worker has successfully processed a trigger
type TriggerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The data returned in the response
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// The context of the request response
	// Typically this will be one to one with the Trigger Context
	// i.e. if you receive http context you may return http context
	//
	// Types that are assignable to Context:
	//	*TriggerResponse_Http
	//	*TriggerResponse_Topic
	Context isTriggerResponse_Context `protobuf_oneof:"context"`
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (m *TriggerResponse) GetContext() isTriggerResponse_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (x *TriggerResponse) GetHttp() *HttpResponseContext {
	if x, ok := x.GetContext().(*TriggerResponse_Http); ok {
		return x.Http
	}
	return nil
}

func (x *TriggerResponse) GetTopic() *TopicResponseContext {
	if x, ok := x.GetContext().(*TriggerResponse_Topic); ok {
		return x.Topic
	}
	return nil
}

type isTriggerResponse_Context interface {
	isTriggerResponse_Context()
}

type TriggerResponse_Http struct {
	// response to a http request
	Http *HttpResponseContext `protobuf:"bytes,10,opt,name=http,proto3,oneof"`
}

type TriggerResponse_Topic struct {
	// response to a topic trigger
	Topic *TopicResponseContext `protobuf:"bytes,11,opt,name=topic,proto3,oneof"`
}

func (*TriggerResponse_Http) isTriggerResponse_Context() {}

func (*TriggerResponse_Topic) isTriggerResponse_Context() {}

// Specific HttpResponse message
// Note this does not have to be handled by the
// User at all but they will have the option of control
// If they choose...
type HttpResponseContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The request headers...
	Headers map[string]string `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// The HTTP status of the request
	Status int32 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *HttpResponseContext) Reset() {
	*x = HttpResponseContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HttpResponseContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponseContext) ProtoMessage() {}

func (x *HttpResponseContext) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponseContext.ProtoReflect.Descriptor instead.
func (*HttpResponseContext) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{8}
}

func (x *HttpResponseContext) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponseContext) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Specific event response message
// We do not accept responses for events
// only whether or not they were successfully processed
type TopicResponseContext struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Success status of the handled event
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *TopicResponseContext) Reset() {
	*x = TopicResponseContext{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faas_v1_faas_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopicResponseContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicResponseContext) ProtoMessage() {}

func (x *TopicResponseContext) ProtoReflect() protoreflect.Message {
	mi := &file_faas_v1_faas_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicResponseContext.ProtoReflect.Descriptor instead.
func (*TopicResponseContext) Descriptor() ([]byte, []int) {
	return file_faas_v1_faas_proto_rawDescGZIP(), []int{9}
}

func (x *TopicResponseContext) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_faas_v1_faas_proto protoreflect.FileDescriptor

var file_faas_v1_faas_proto_rawDesc = []byte{
	0x0a, 0x12, 0x66, 0x61, 0x61, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61,
	0x73, 0x2e, 0x76, 0x31, 0x22, 0xba, 0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x40, 0x0a, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6e,
	0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e,
	0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x69, 0x6e, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x10, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0f, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x22, 0xba, 0x01, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x43, 0x0a, 0x0d, 0x69, 0x6e, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6e, 0x69, 0x74,
	0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0f, 0x74, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0e, 0x74, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x0d,
	0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x49, 0x6e, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc3, 0x01,
	0x0a, 0x0e, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x38, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x48, 0x74, 0x74, 0x70, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x12, 0x3b, 0x0a, 0x05, 0x74,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x69, 0x74,
	0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48,
	0x00, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x22, 0xdf, 0x02, 0x0a, 0x12, 0x48, 0x74, 0x74, 0x70, 0x54, 0x72, 0x69, 0x67,
	0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x49, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x12, 0x56, 0x0a, 0x0c, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x54, 0x72, 0x69,
	0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3e, 0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x2b, 0x0a, 0x13, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x54, 0x72,
	0x69, 0x67, 0x67, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70,
	0x69, 0x63, 0x22, 0xa9, 0x01, 0x0a, 0x0f, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x39, 0x0a, 0x04, 0x68, 0x74,
	0x74, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69,
	0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52,
	0x04, 0x68, 0x74, 0x74, 0x70, 0x12, 0x3c, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61,
	0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0xb5,
	0x01, 0x0a, 0x13, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x4a, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x14, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x59, 0x0a, 0x04, 0x46, 0x61, 0x61, 0x73,
	0x12, 0x51, 0x0a, 0x0d, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x1d, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x1a, 0x1d, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x42, 0x63, 0x0a, 0x17, 0x69, 0x6f, 0x2e, 0x6e, 0x69, 0x74, 0x72, 0x69, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x61, 0x61, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x0a,
	0x4e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x46, 0x61, 0x61, 0x73, 0x50, 0x01, 0x5a, 0x0c, 0x6e, 0x69,
	0x74, 0x72, 0x69, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0xaa, 0x02, 0x14, 0x4e, 0x69, 0x74,
	0x72, 0x69, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x61, 0x61, 0x73, 0x2e, 0x76,
	0x31, 0xca, 0x02, 0x14, 0x4e, 0x69, 0x74, 0x72, 0x69, 0x63, 0x5c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x5c, 0x46, 0x61, 0x61, 0x73, 0x5c, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faas_v1_faas_proto_rawDescOnce sync.Once
	file_faas_v1_faas_proto_rawDescData = file_faas_v1_faas_proto_rawDesc
)

func file_faas_v1_faas_proto_rawDescGZIP() []byte {
	file_faas_v1_faas_proto_rawDescOnce.Do(func() {
		file_faas_v1_faas_proto_rawDescData = protoimpl.X.CompressGZIP(file_faas_v1_faas_proto_rawDescData)
	})
	return file_faas_v1_faas_proto_rawDescData
}

var file_faas_v1_faas_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_faas_v1_faas_proto_goTypes = []interface{}{
	(*ClientMessage)(nil),        // 0: nitric.faas.v1.ClientMessage
	(*ServerMessage)(nil),        // 1: nitric.faas.v1.ServerMessage
	(*InitRequest)(nil),          // 2: nitric.faas.v1.InitRequest
	(*InitResponse)(nil),         // 3: nitric.faas.v1.InitResponse
	(*TriggerRequest)(nil),       // 4: nitric.faas.v1.TriggerRequest
	(*HttpTriggerContext)(nil),   // 5: nitric.faas.v1.HttpTriggerContext
	(*TopicTriggerContext)(nil),  // 6: nitric.faas.v1.TopicTriggerContext
	(*TriggerResponse)(nil),      // 7: nitric.faas.v1.TriggerResponse
	(*HttpResponseContext)(nil),  // 8: nitric.faas.v1.HttpResponseContext
	(*TopicResponseContext)(nil), // 9: nitric.faas.v1.TopicResponseContext
	nil,                          // 10: nitric.faas.v1.HttpTriggerContext.HeadersEntry
	nil,                          // 11: nitric.faas.v1.HttpTriggerContext.QueryParamsEntry
	nil,                          // 12: nitric.faas.v1.HttpResponseContext.HeadersEntry
}
var file_faas_v1_faas_proto_depIdxs = []int32{
	2,  // 0: nitric.faas.v1.ClientMessage.init_request:type_name -> nitric.faas.v1.InitRequest
	7,  // 1: nitric.faas.v1.ClientMessage.trigger_response:type_name -> nitric.faas.v1.TriggerResponse
	3,  // 2: nitric.faas.v1.ServerMessage.init_response:type_name -> nitric.faas.v1.InitResponse
	4,  // 3: nitric.faas.v1.ServerMessage.trigger_request:type_name -> nitric.faas.v1.TriggerRequest
	5,  // 4: nitric.faas.v1.TriggerRequest.http:type_name -> nitric.faas.v1.HttpTriggerContext
	6,  // 5: nitric.faas.v1.TriggerRequest.topic:type_name -> nitric.faas.v1.TopicTriggerContext
	10, // 6: nitric.faas.v1.HttpTriggerContext.headers:type_name -> nitric.faas.v1.HttpTriggerContext.HeadersEntry
	11, // 7: nitric.faas.v1.HttpTriggerContext.query_params:type_name -> nitric.faas.v1.HttpTriggerContext.QueryParamsEntry
	8,  // 8: nitric.faas.v1.TriggerResponse.http:type_name -> nitric.faas.v1.HttpResponseContext
	9,  // 9: nitric.faas.v1.TriggerResponse.topic:type_name -> nitric.faas.v1.TopicResponseContext
	12, // 10: nitric.faas.v1.HttpResponseContext.headers:type_name -> nitric.faas.v1.HttpResponseContext.HeadersEntry
	0,  // 11: nitric.faas.v1.Faas.TriggerStream:input_type -> nitric.faas.v1.ClientMessage
	1,  // 12: nitric.faas.v1.Faas.TriggerStream:output_type -> nitric.faas.v1.ServerMessage
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_faas_v1_faas_proto_init() }
func file_faas_v1_faas_proto_init() {
	if File_faas_v1_faas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_faas_v1_faas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpTriggerContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicTriggerContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriggerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HttpResponseContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faas_v1_faas_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopicResponseContext); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_faas_v1_faas_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ClientMessage_InitRequest)(nil),
		(*ClientMessage_TriggerResponse)(nil),
	}
	file_faas_v1_faas_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ServerMessage_InitResponse)(nil),
		(*ServerMessage_TriggerRequest)(nil),
	}
	file_faas_v1_faas_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*TriggerRequest_Http)(nil),
		(*TriggerRequest_Topic)(nil),
	}
	file_faas_v1_faas_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*TriggerResponse_Http)(nil),
		(*TriggerResponse_Topic)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faas_v1_faas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faas_v1_faas_proto_goTypes,
		DependencyIndexes: file_faas_v1_faas_proto_depIdxs,
		MessageInfos:      file_faas_v1_faas_proto_msgTypes,
	}.Build()
	File_faas_v1_faas_proto = out.File
	file_faas_v1_faas_proto_rawDesc = nil
	file_faas_v1_faas_proto_goTypes = nil
	file_faas_v1_faas_proto_depIdxs = nil
}
