// Code generated by protoc-gen-go. DO NOT EDIT.
// source: secret/v1/secret.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request to put a secret to a Secret Store
type SecretPutRequest struct {
	// The Secret to put to the Secret store
	Secret *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// The value to assign to that secret
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretPutRequest) Reset()         { *m = SecretPutRequest{} }
func (m *SecretPutRequest) String() string { return proto.CompactTextString(m) }
func (*SecretPutRequest) ProtoMessage()    {}
func (*SecretPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52cae2698389aae, []int{0}
}

func (m *SecretPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretPutRequest.Unmarshal(m, b)
}
func (m *SecretPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretPutRequest.Marshal(b, m, deterministic)
}
func (m *SecretPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretPutRequest.Merge(m, src)
}
func (m *SecretPutRequest) XXX_Size() int {
	return xxx_messageInfo_SecretPutRequest.Size(m)
}
func (m *SecretPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretPutRequest proto.InternalMessageInfo

func (m *SecretPutRequest) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *SecretPutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// Result from putting the secret to a Secret Store
type SecretPutResponse struct {
	// The id of the secret
	SecretVersion        *SecretVersion `protobuf:"bytes,1,opt,name=secret_version,json=secretVersion,proto3" json:"secret_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SecretPutResponse) Reset()         { *m = SecretPutResponse{} }
func (m *SecretPutResponse) String() string { return proto.CompactTextString(m) }
func (*SecretPutResponse) ProtoMessage()    {}
func (*SecretPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52cae2698389aae, []int{1}
}

func (m *SecretPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretPutResponse.Unmarshal(m, b)
}
func (m *SecretPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretPutResponse.Marshal(b, m, deterministic)
}
func (m *SecretPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretPutResponse.Merge(m, src)
}
func (m *SecretPutResponse) XXX_Size() int {
	return xxx_messageInfo_SecretPutResponse.Size(m)
}
func (m *SecretPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretPutResponse proto.InternalMessageInfo

func (m *SecretPutResponse) GetSecretVersion() *SecretVersion {
	if m != nil {
		return m.SecretVersion
	}
	return nil
}

// Request to get a secret from a Secret Store
type SecretAccessRequest struct {
	// The id of the secret
	SecretVersion        *SecretVersion `protobuf:"bytes,1,opt,name=secret_version,json=secretVersion,proto3" json:"secret_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SecretAccessRequest) Reset()         { *m = SecretAccessRequest{} }
func (m *SecretAccessRequest) String() string { return proto.CompactTextString(m) }
func (*SecretAccessRequest) ProtoMessage()    {}
func (*SecretAccessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52cae2698389aae, []int{2}
}

func (m *SecretAccessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretAccessRequest.Unmarshal(m, b)
}
func (m *SecretAccessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretAccessRequest.Marshal(b, m, deterministic)
}
func (m *SecretAccessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretAccessRequest.Merge(m, src)
}
func (m *SecretAccessRequest) XXX_Size() int {
	return xxx_messageInfo_SecretAccessRequest.Size(m)
}
func (m *SecretAccessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretAccessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SecretAccessRequest proto.InternalMessageInfo

func (m *SecretAccessRequest) GetSecretVersion() *SecretVersion {
	if m != nil {
		return m.SecretVersion
	}
	return nil
}

// The secret response
type SecretAccessResponse struct {
	// The version of the secret that was requested
	SecretVersion *SecretVersion `protobuf:"bytes,1,opt,name=secret_version,json=secretVersion,proto3" json:"secret_version,omitempty"`
	// The value of the secret
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretAccessResponse) Reset()         { *m = SecretAccessResponse{} }
func (m *SecretAccessResponse) String() string { return proto.CompactTextString(m) }
func (*SecretAccessResponse) ProtoMessage()    {}
func (*SecretAccessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52cae2698389aae, []int{3}
}

func (m *SecretAccessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretAccessResponse.Unmarshal(m, b)
}
func (m *SecretAccessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretAccessResponse.Marshal(b, m, deterministic)
}
func (m *SecretAccessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretAccessResponse.Merge(m, src)
}
func (m *SecretAccessResponse) XXX_Size() int {
	return xxx_messageInfo_SecretAccessResponse.Size(m)
}
func (m *SecretAccessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretAccessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SecretAccessResponse proto.InternalMessageInfo

func (m *SecretAccessResponse) GetSecretVersion() *SecretVersion {
	if m != nil {
		return m.SecretVersion
	}
	return nil
}

func (m *SecretAccessResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

// The secret container
type Secret struct {
	// The secret name
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52cae2698389aae, []int{4}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// A version of a secret
type SecretVersion struct {
	// Reference to the secret container
	Secret *Secret `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	// The secret version
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SecretVersion) Reset()         { *m = SecretVersion{} }
func (m *SecretVersion) String() string { return proto.CompactTextString(m) }
func (*SecretVersion) ProtoMessage()    {}
func (*SecretVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_b52cae2698389aae, []int{5}
}

func (m *SecretVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SecretVersion.Unmarshal(m, b)
}
func (m *SecretVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SecretVersion.Marshal(b, m, deterministic)
}
func (m *SecretVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SecretVersion.Merge(m, src)
}
func (m *SecretVersion) XXX_Size() int {
	return xxx_messageInfo_SecretVersion.Size(m)
}
func (m *SecretVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_SecretVersion.DiscardUnknown(m)
}

var xxx_messageInfo_SecretVersion proto.InternalMessageInfo

func (m *SecretVersion) GetSecret() *Secret {
	if m != nil {
		return m.Secret
	}
	return nil
}

func (m *SecretVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*SecretPutRequest)(nil), "nitric.secret.v1.SecretPutRequest")
	proto.RegisterType((*SecretPutResponse)(nil), "nitric.secret.v1.SecretPutResponse")
	proto.RegisterType((*SecretAccessRequest)(nil), "nitric.secret.v1.SecretAccessRequest")
	proto.RegisterType((*SecretAccessResponse)(nil), "nitric.secret.v1.SecretAccessResponse")
	proto.RegisterType((*Secret)(nil), "nitric.secret.v1.Secret")
	proto.RegisterType((*SecretVersion)(nil), "nitric.secret.v1.SecretVersion")
}

func init() { proto.RegisterFile("secret/v1/secret.proto", fileDescriptor_b52cae2698389aae) }

var fileDescriptor_b52cae2698389aae = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x4e, 0x4d, 0x2e,
	0x4a, 0x2d, 0xd1, 0x2f, 0x33, 0xd4, 0x87, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x04,
	0xf2, 0x32, 0x4b, 0x8a, 0x32, 0x93, 0xf5, 0xa0, 0x82, 0x65, 0x86, 0x52, 0xe2, 0x65, 0x89, 0x39,
	0x99, 0x29, 0x89, 0x25, 0xa9, 0xfa, 0x30, 0x06, 0x44, 0xa9, 0x52, 0x0a, 0x97, 0x40, 0x30, 0x58,
	0x55, 0x40, 0x69, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x15, 0x17, 0x1b, 0x44,
	0xa7, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0xb7, 0x91, 0x84, 0x1e, 0xba, 0x79, 0x7a, 0x10, 0x3d, 0x4e,
	0x1c, 0xbf, 0x9c, 0x58, 0xbb, 0x18, 0x99, 0x04, 0x18, 0x83, 0xa0, 0x3a, 0x84, 0x44, 0xb8, 0x58,
	0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0x20, 0x1c, 0xa5, 0x68,
	0x2e, 0x41, 0x24, 0x5b, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xdc, 0xb8, 0xf8, 0x20, 0x9a,
	0xe2, 0xcb, 0x52, 0x8b, 0x8a, 0x33, 0xf3, 0xf3, 0xa0, 0xd6, 0xc9, 0xe3, 0xb2, 0x2e, 0x0c, 0xa2,
	0x2c, 0x88, 0xb7, 0x18, 0x99, 0xab, 0x94, 0xce, 0x25, 0x0c, 0x91, 0x77, 0x4c, 0x4e, 0x4e, 0x2d,
	0x2e, 0x86, 0xf9, 0x22, 0x80, 0x4c, 0xe3, 0x91, 0x3c, 0x85, 0x66, 0x51, 0x27, 0x23, 0x97, 0x08,
	0xaa, 0x4d, 0x50, 0x9f, 0x50, 0xdd, 0x2a, 0x21, 0x79, 0x94, 0x60, 0x74, 0xe2, 0xfc, 0xe5, 0xc4,
	0x56, 0xc5, 0x22, 0x71, 0x60, 0x37, 0x23, 0x2c, 0x44, 0x2d, 0xb8, 0xd8, 0x20, 0x46, 0x09, 0xe9,
	0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x82, 0xad, 0xe4, 0x74, 0x92, 0xfa, 0xe5, 0x24, 0x5e, 0x24,
	0xaa, 0xd1, 0xc0, 0x64, 0x24, 0x10, 0x17, 0x53, 0xae, 0xad, 0x11, 0xad, 0x17, 0xa3, 0x1b, 0x1b,
	0x53, 0xae, 0xad, 0xa9, 0xa5, 0x12, 0x04, 0x56, 0xa7, 0x94, 0xc7, 0xc5, 0x8b, 0xe2, 0x08, 0x8a,
	0xa2, 0x5b, 0x91, 0x8b, 0x1d, 0xe6, 0x65, 0x26, 0xb0, 0xfd, 0xec, 0xbf, 0x9c, 0x58, 0x8a, 0x40,
	0x2a, 0x60, 0xe2, 0x46, 0x3b, 0x18, 0x61, 0x16, 0x06, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a,
	0xf9, 0x71, 0x31, 0x07, 0x94, 0x96, 0x08, 0x29, 0xe1, 0xb2, 0x07, 0x91, 0x14, 0xa5, 0x94, 0xf1,
	0xaa, 0x81, 0x06, 0x7f, 0x38, 0x17, 0x1b, 0x24, 0x42, 0x84, 0x54, 0x71, 0x29, 0x47, 0x49, 0x1a,
	0x52, 0x6a, 0x84, 0x94, 0x41, 0x0c, 0x76, 0x4a, 0xe3, 0x92, 0xcc, 0xcc, 0x87, 0xa9, 0x05, 0xe7,
	0x17, 0x84, 0x0e, 0x27, 0x76, 0x88, 0x96, 0xe2, 0x00, 0xc6, 0x28, 0x1e, 0x88, 0x12, 0xfd, 0x32,
	0x43, 0xeb, 0x32, 0xc3, 0x55, 0x4c, 0x62, 0x7e, 0x10, 0x1d, 0x01, 0x60, 0x1d, 0xc1, 0x30, 0x1d,
	0xa7, 0x60, 0x12, 0x31, 0x60, 0x89, 0x18, 0x88, 0x44, 0x4c, 0x98, 0x61, 0x12, 0x1b, 0xd8, 0x6c,
	0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x06, 0xa8, 0xee, 0xd0, 0x03, 0x00, 0x00,
}
