// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage/v1/storage.proto

package v1

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request to put (create/update) a storage item
type StorageWriteRequest struct {
	// Nitric name of the bucket to store in
	//  this will be automatically resolved to the provider specific bucket identifier.
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// Key to store the item under
	Key string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// bytes array to store
	Body                 []byte   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageWriteRequest) Reset()         { *m = StorageWriteRequest{} }
func (m *StorageWriteRequest) String() string { return proto.CompactTextString(m) }
func (*StorageWriteRequest) ProtoMessage()    {}
func (*StorageWriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7404b6916b5670ce, []int{0}
}

func (m *StorageWriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageWriteRequest.Unmarshal(m, b)
}
func (m *StorageWriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageWriteRequest.Marshal(b, m, deterministic)
}
func (m *StorageWriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageWriteRequest.Merge(m, src)
}
func (m *StorageWriteRequest) XXX_Size() int {
	return xxx_messageInfo_StorageWriteRequest.Size(m)
}
func (m *StorageWriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageWriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageWriteRequest proto.InternalMessageInfo

func (m *StorageWriteRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *StorageWriteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StorageWriteRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// Result of putting a storage item
type StorageWriteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageWriteResponse) Reset()         { *m = StorageWriteResponse{} }
func (m *StorageWriteResponse) String() string { return proto.CompactTextString(m) }
func (*StorageWriteResponse) ProtoMessage()    {}
func (*StorageWriteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7404b6916b5670ce, []int{1}
}

func (m *StorageWriteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageWriteResponse.Unmarshal(m, b)
}
func (m *StorageWriteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageWriteResponse.Marshal(b, m, deterministic)
}
func (m *StorageWriteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageWriteResponse.Merge(m, src)
}
func (m *StorageWriteResponse) XXX_Size() int {
	return xxx_messageInfo_StorageWriteResponse.Size(m)
}
func (m *StorageWriteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageWriteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageWriteResponse proto.InternalMessageInfo

// Request to retrieve a storage item
type StorageReadRequest struct {
	// Nitric name of the bucket to retrieve from
	//  this will be automatically resolved to the provider specific bucket identifier.
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// Key of item to retrieve
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageReadRequest) Reset()         { *m = StorageReadRequest{} }
func (m *StorageReadRequest) String() string { return proto.CompactTextString(m) }
func (*StorageReadRequest) ProtoMessage()    {}
func (*StorageReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7404b6916b5670ce, []int{2}
}

func (m *StorageReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageReadRequest.Unmarshal(m, b)
}
func (m *StorageReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageReadRequest.Marshal(b, m, deterministic)
}
func (m *StorageReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageReadRequest.Merge(m, src)
}
func (m *StorageReadRequest) XXX_Size() int {
	return xxx_messageInfo_StorageReadRequest.Size(m)
}
func (m *StorageReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageReadRequest proto.InternalMessageInfo

func (m *StorageReadRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *StorageReadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Returned storage item
type StorageReadResponse struct {
	// The body bytes of the retrieved storage item
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageReadResponse) Reset()         { *m = StorageReadResponse{} }
func (m *StorageReadResponse) String() string { return proto.CompactTextString(m) }
func (*StorageReadResponse) ProtoMessage()    {}
func (*StorageReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7404b6916b5670ce, []int{3}
}

func (m *StorageReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageReadResponse.Unmarshal(m, b)
}
func (m *StorageReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageReadResponse.Marshal(b, m, deterministic)
}
func (m *StorageReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageReadResponse.Merge(m, src)
}
func (m *StorageReadResponse) XXX_Size() int {
	return xxx_messageInfo_StorageReadResponse.Size(m)
}
func (m *StorageReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageReadResponse proto.InternalMessageInfo

func (m *StorageReadResponse) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// Request to delete a storage item
type StorageDeleteRequest struct {
	// Name of the bucket to delete from
	BucketName string `protobuf:"bytes,1,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	// Key of item to delete
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageDeleteRequest) Reset()         { *m = StorageDeleteRequest{} }
func (m *StorageDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*StorageDeleteRequest) ProtoMessage()    {}
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7404b6916b5670ce, []int{4}
}

func (m *StorageDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageDeleteRequest.Unmarshal(m, b)
}
func (m *StorageDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageDeleteRequest.Marshal(b, m, deterministic)
}
func (m *StorageDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageDeleteRequest.Merge(m, src)
}
func (m *StorageDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_StorageDeleteRequest.Size(m)
}
func (m *StorageDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StorageDeleteRequest proto.InternalMessageInfo

func (m *StorageDeleteRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *StorageDeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

// Result of deleting a storage item
type StorageDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageDeleteResponse) Reset()         { *m = StorageDeleteResponse{} }
func (m *StorageDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*StorageDeleteResponse) ProtoMessage()    {}
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7404b6916b5670ce, []int{5}
}

func (m *StorageDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageDeleteResponse.Unmarshal(m, b)
}
func (m *StorageDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageDeleteResponse.Marshal(b, m, deterministic)
}
func (m *StorageDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageDeleteResponse.Merge(m, src)
}
func (m *StorageDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_StorageDeleteResponse.Size(m)
}
func (m *StorageDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorageDeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*StorageWriteRequest)(nil), "nitric.storage.v1.StorageWriteRequest")
	proto.RegisterType((*StorageWriteResponse)(nil), "nitric.storage.v1.StorageWriteResponse")
	proto.RegisterType((*StorageReadRequest)(nil), "nitric.storage.v1.StorageReadRequest")
	proto.RegisterType((*StorageReadResponse)(nil), "nitric.storage.v1.StorageReadResponse")
	proto.RegisterType((*StorageDeleteRequest)(nil), "nitric.storage.v1.StorageDeleteRequest")
	proto.RegisterType((*StorageDeleteResponse)(nil), "nitric.storage.v1.StorageDeleteResponse")
}

func init() { proto.RegisterFile("storage/v1/storage.proto", fileDescriptor_7404b6916b5670ce) }

var fileDescriptor_7404b6916b5670ce = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xcd, 0x4e, 0xc2, 0x40,
	0x10, 0xc7, 0xd3, 0x82, 0x44, 0x47, 0x62, 0x70, 0x15, 0xdb, 0xf4, 0x44, 0x1a, 0x3f, 0x8a, 0xc4,
	0x36, 0xc5, 0x23, 0xb7, 0xc6, 0x33, 0x21, 0x25, 0x7e, 0x44, 0xaa, 0xa6, 0x94, 0x89, 0xa9, 0x7c,
	0x14, 0xdb, 0xa5, 0xc8, 0xcd, 0x27, 0xf1, 0x01, 0x7c, 0x14, 0x1f, 0xc9, 0x93, 0xa1, 0xbb, 0x6d,
	0x40, 0x12, 0x38, 0x71, 0x9b, 0xec, 0xfc, 0x7f, 0x33, 0xff, 0x99, 0x1d, 0x90, 0x23, 0x1a, 0x84,
	0xee, 0x2b, 0x1a, 0xb1, 0x69, 0xf0, 0x50, 0x1f, 0x87, 0x01, 0x0d, 0xc8, 0xe1, 0xc8, 0xa7, 0xa1,
	0xef, 0xe9, 0xe9, 0x6b, 0x6c, 0x2a, 0x52, 0xec, 0x0e, 0xfc, 0x9e, 0x4b, 0xd1, 0x48, 0x03, 0xa6,
	0x55, 0x3f, 0xe0, 0xa8, 0xcd, 0x64, 0xf7, 0xa1, 0x4f, 0xd1, 0xc6, 0xf7, 0x09, 0x46, 0x94, 0x34,
	0x60, 0xbf, 0x3b, 0xf1, 0xfa, 0x48, 0x5f, 0x46, 0xee, 0x10, 0x65, 0xa1, 0x22, 0x68, 0x7b, 0x96,
	0xf2, 0x6b, 0x49, 0x61, 0x59, 0xfb, 0x14, 0xeb, 0xa5, 0x67, 0x67, 0x5a, 0xd3, 0x3a, 0xba, 0x73,
	0xf5, 0xe4, 0x4c, 0x6b, 0xd5, 0xcb, 0x53, 0x1b, 0x98, 0xbc, 0xe9, 0x0e, 0x91, 0x94, 0x20, 0xd7,
	0xc7, 0x99, 0x2c, 0xce, 0x21, 0x7b, 0x1e, 0x12, 0x02, 0xf9, 0x6e, 0xd0, 0x9b, 0xc9, 0xb9, 0x8a,
	0xa0, 0x15, 0xed, 0x24, 0x56, 0x4f, 0xe0, 0x78, 0xb9, 0x73, 0x34, 0x0e, 0x46, 0x11, 0xaa, 0x1e,
	0x10, 0xfe, 0x6e, 0xa3, 0xdb, 0xdb, 0x8e, 0x21, 0xb5, 0x9a, 0x8d, 0xcd, 0x9a, 0xb0, 0xde, 0x99,
	0x4f, 0x61, 0xc1, 0x27, 0x66, 0x3e, 0x6f, 0x70, 0x80, 0xdb, 0x5a, 0x91, 0x2a, 0x41, 0xf9, 0x5f,
	0x1b, 0xe6, 0xa9, 0xfe, 0x25, 0xc2, 0x01, 0xcf, 0xb4, 0x31, 0x8c, 0x7d, 0x0f, 0xc9, 0x2d, 0xe4,
	0xe7, 0xb6, 0xc9, 0x99, 0xbe, 0xf2, 0xd3, 0xfa, 0xea, 0xee, 0x94, 0xf3, 0x4d, 0x32, 0x3e, 0xfd,
	0x03, 0xec, 0x24, 0x5f, 0x41, 0xd6, 0x00, 0x8b, 0x57, 0xa2, 0x5c, 0x6c, 0xd4, 0xf1, 0xca, 0x1d,
	0x28, 0xb0, 0xa9, 0xc8, 0x1a, 0x64, 0x69, 0xbd, 0x8a, 0xb6, 0x59, 0xc8, 0x8a, 0x5b, 0x6f, 0xa0,
	0xf8, 0x41, 0xaa, 0x4e, 0xae, 0x7a, 0x81, 0xb1, 0x76, 0x39, 0x14, 0xb5, 0x84, 0xc7, 0x22, 0x13,
	0x19, 0xb1, 0xd9, 0x88, 0xcd, 0x6f, 0x51, 0x6a, 0x32, 0xa6, 0x95, 0x30, 0xed, 0x8c, 0xf9, 0x49,
	0x33, 0x4e, 0x92, 0x71, 0x78, 0xc6, 0xb9, 0x33, 0xbb, 0x85, 0xa4, 0xfe, 0xf5, 0x5f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xcb, 0xdd, 0xec, 0x36, 0x7d, 0x03, 0x00, 0x00,
}
